language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - wget https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
  - wget https://www.libsdl.org/release/SDL2-devel-2.0.5-mingw.tar.gz
  - mkdir gnu-mingw/dll/32
  - mkdir gnu-mingw/dll/64
  - mkdir gnu-mingw/lib/32
  - mkdir gnu-mingw/lib/64
  - mkdir msvc/dll/32
  - mkdir msvc/dll/64
  - mkdir msvc/lib/32
  - mkdir msvc/lib/64
  - 7z x SDL2-devel-2.0.5-mingw.tar.gz
  - 7z x SDL2-devel-2.0.5-mingw.tar
  - cp SDL2-2.0.5/i686-w64-mingw32/bin/SDL2.dll gnu-mingw/dll/32
  - cp SDL2-2.0.5/i686-w64-mingw32/lib/libSDL2.a gnu-mingw/lib/32
  - cp SDL2-2.0.5/i686-w64-mingw32/lib/libSDL2.dll.a gnu-mingw/lib/32
  - cp SDL2-2.0.5/i686-w64-mingw32/lib/libSDL2.la gnu-mingw/lib/32
  - cp SDL2-2.0.5/i686-w64-mingw32/lib/libSDL2_test.a gnu-mingw/lib/32
  - cp SDL2-2.0.5/i686-w64-mingw32/lib/libSDL2main.a gnu-mingw/lib/32
  - cp SDL2-2.0.5/x86_64-w64-mingw32/bin/SDL2.dll gnu-mingw/dll/64
  - cp SDL2-2.0.5/x86_64-w64-mingw32/lib/libSDL2.a gnu-mingw/lib/64
  - cp SDL2-2.0.5/x86_64-w64-mingw32/lib/libSDL2.dll.a gnu-mingw/lib/64
  - cp SDL2-2.0.5/x86_64-w64-mingw32/lib/libSDL2.la gnu-mingw/lib/64
  - cp SDL2-2.0.5/x86_64-w64-mingw32/lib/libSDL2_test.a gnu-mingw/lib/64
  - cp SDL2-2.0.5/x86_64-w64-mingw32/lib/libSDL2main.a gnu-mingw/lib/64
  - rm -r SDL2-2.0.5
  - 7z x SDL2-devel-2.0.5-VC.zip
  - cp SDL2-2.0.5/lib/x86/SDL2.dll msvc/dll/32
  - cp SDL2-2.0.5/lib/x86/SDL2.lib msvc/lib/32
  - cp SDL2-2.0.5/lib/x86/SDL2main.lib msvc/lib/32
  - cp SDL2-2.0.5/lib/x86/SDL2test.lib msvc/lib/32
  - cp SDL2-2.0.5/lib/x64/SDL2.dll msvc/dll/64
  - cp SDL2-2.0.5/lib/x64/SDL2.lib msvc/lib/64
  - cp SDL2-2.0.5/lib/x64/SDL2main.lib msvc/lib/64
  - cp SDL2-2.0.5/lib/x64/SDL2test.lib msvc/lib/64
  - rm -r SDL2-2.0.5

